version: "3.9"
services:
  app:
    build: .
    container_name: api-car-service
    env_file: .env
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - api_network
    depends_on:
      - mongo
    command: ["sh", "-c", "npx prisma generate dev && npx nodemon --exec 'npm run start'"]


  mongo:
    image: mongo
    container_name: mongo-db
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

networks:
  api_network: {}
