version: "3.9"
services:
  app:
    build: .
    container_name: api-car-service
    env_file: .env
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - api_network
      - rabbitmq_nodejs
    depends_on:
      - mongo
      - rabbitmq
    command:
      [
        "sh",
        "-c",
        "npx nodemon --exec 'npm run start'",
      ]

  mongo:
    image: mongo
    container_name: mongo-db
    volumes:
      - db-data:/var/lib/mongo
    ports:
      - "27017:27017"
    networks:
      - api_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - api_network

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: nodejs-rabbitmq-rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - rabbitmq_nodejs

networks:
  rabbitmq_nodejs:
    driver: bridge
  api_network: 
    driver: bridge

volumes:
  db-data: {}
  rabbitmq-data: {}
